services:

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    ports:
      - "8090:80"
    volumes:
      - ./src:/var/www/html

  db:
    image: mariadb:11
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: trial2
      MARIADB_USER: trial2
      MARIADB_PASSWORD: trial2
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: db
    ports:
      - "8091:80"
    depends_on:
      - db

volumes:
  db_data: